# Generated by Django 3.2.7 on 2021-10-26 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0002_alter_post_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'Статья ', 'verbose_name_plural': 'Статьи'},
        ),
    ]
